// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserControllerInterface is an autogenerated mock type for the UserControllerInterface type
type UserControllerInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *UserControllerInterface) Login(c *gin.Context) {
	_m.Called(c)
}

// NewUserControllerInterface creates a new instance of UserControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserControllerInterface {
	mock := &UserControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
