// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	request "backend/dto/request"

	mock "github.com/stretchr/testify/mock"
)

// UserDaoInterface is an autogenerated mock type for the UserDaoInterface type
type UserDaoInterface struct {
	mock.Mock
}

// GetUserByName provides a mock function with given fields: req
func (_m *UserDaoInterface) GetUserByName(req *request.UserLoginReq) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*request.UserLoginReq) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserDaoInterface creates a new instance of UserDaoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDaoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDaoInterface {
	mock := &UserDaoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
